#!/bin/bash
#  a script to automate building and publishing changes to my website
echo 'Using sphinx to rebuild the site'
make clean
make html
echo ' '
echo 'Using rsync to update the www folder on reed.'
rsync -r _build/html/ br546577@reed.atmos.albany.edu:/nfs/home11/staff/brose/www/
echo 'Publishing complete.'
